language: python
dist: trusty
sudo: required
python:
    - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep -qq python-pygame
    - sudo apt-get install -qq mercurial
install:
    - pip install hg+http://bitbucket.org/pygame/pygame
    - pip install codecov
    - pip install pytest
    - pip install pytest-cov
script:
    - sed -i '/def main():/a \   \ os.environ["SDL_VIDEODRIVER"] = "x11"' game/__init__.py
    - sed -i 's/set_mode( (0,0)/set_mode( (800, 600)/' game/__init__.py
    - python setup.py install
    # py.test --cov=./ tests/tests.py
    - py.test --cov=./ tests.py
after_success:
    - codecov
